<?php

/**
 * PluginmajaxMediaFileDataTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmajaxMediaFileDataTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginmajaxMediaFileDataTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginmajaxMediaFileData');
  }
}