<?php

/**
 * PluginmajaxMediaFileInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmajaxMediaFileInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmajaxMediaFileInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmajaxMediaFileInfo');
    }
}