<?php

/**
 * PluginmajaxMediaFileData
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmajaxMediaFileData extends BasemajaxMediaFileData
{
  protected $dFilePath = null;

  /**
   * @return string
   */
  public function fetchFilePath()
  {
    if ($this->dFilePath == null) {
      $n = tempnam('/tmp', 'file_data');
      unlink($n);
      mkdir($n);
      $f = $n . '/' . $this->FileInfo->name;
      file_put_contents($f, $this->binary_data);
      $this->dFilePath = $f;
    }
    return $this->dFilePath;
  }

  public function unlinkFilePath()
  {
    if ($this->dFilePath == null)
      return;
    $d = dirname($this->dFilePath);
    @shell_exec('rm -rf ' . escapeshellarg($d));
  }
}
