<?php

/**
 * PluginmajaxMediaPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmajaxMediaPhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmajaxMediaPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmajaxMediaPhoto');
    }
}