<?php

/**
 * PluginmajaxMediaAudio
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmajaxMediaAudio extends BasemajaxMediaAudio
{
  public function setUp()
  {
    parent::setUp();
    if (sfConfig::get('app_majax_media_publishable', false)) {
      $publishabletemplate0 = new PublishableTemplate();
      $this->actAs($publishabletemplate0);
    }
  }

  public function assignDefaultValues($overwrite = false)
  {
    parent::assignDefaultValues($overwrite);
    $this->recorded_on = date('Y-m-d');
  }

  public function postSave($event)
  {
    if ($this->MediaRegistryEntry == null) {
      $mre = new majaxMediaRegistryEntry();
      $mre->audio_media = $this->id;
      $this->MediaRegistryEntry = $mre;
      $this->save();
    }
  }

  protected $contentChanged = false;
  protected $transcriptChanged = false;

  public function setContent($content)
  {
    if ($this->content != $content) {
      $this->_set('content', $content);
      $this->_set('content_html', majaxMarkdown::transform($content));
      $this->contentChanged = true;
    }
  }

  public function setContentHtml($content_html, $override = false)
  {
    if (!$this->contentChanged || $override == true)
      $this->_set('content_html', $content_html);
  }

  public function setTranscript($transcript)
  {
    if ($this->transcript != $transcript) {
      $this->_set('transcript', $transcript);
      $this->_set('transcript_html', majaxMarkdown::transform($transcript));
      $this->transcriptChanged = true;
    }
  }

  public function setTranscriptHtml($transcript_html, $override = false)
  {
    if (!$this->transcriptChanged || $override == true)
      $this->_set('transcript_html', $transcript_html);
  }
}
