<?php

/**
 * PluginmajaxMediaVideoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmajaxMediaVideoTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginmajaxMediaVideoTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginmajaxMediaVideo');
  }
}