<?php

/**
 * PluginmajaxMediaRegistryEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmajaxMediaRegistryEntry extends BasemajaxMediaRegistryEntry
{
  public function assignDefaultValues($overwrite = false)
  {
    parent::assignDefaultValues($overwrite);
    $this->uuid = majaxMediaToolbox::uuid('mre:');
  }
  public function getObject($deep = false)
  {
    if ($this->photo_media > 0)
    {
      if ($this->_get('Photo') == null)
      {
        $q = Doctrine_Query::create()->from('majaxMediaPhoto m');
        $q->where('m.id = ?', $this->photo_media);
        $m = $q->fetchOne();
        $this->_set('Photo', $m);
      }
      return $this->_get('Photo');
    }
    if ($this->video_media > 0)
    {
      if ($this->_get('Video') == null)
      {
        $q = Doctrine_Query::create()->from('majaxMediaVideo m');
        $q->where('m.id = ?', $this->video_media);
        $m = $q->fetchOne();
        $this->_set('Video', $m);
      }
      return $this->_get('Video');
    }
    if ($this->audio_media > 0)
    {
      if ($this->_get('Audio') == null)
      {
        $q = Doctrine_Query::create()->from('majaxMediaAudio m');
        $q->where('m.id = ?', $this->audio_media);
        $m = $q->fetchOne();
        $this->_set('Audio', $m);
      }
      return $this->_get('Audio');
    }
    if ($this->gallery_media > 0)
    {
      if ($this->_get('Gallery') == null)
      {
        $q = Doctrine_Query::create()->from('majaxMediaGallery g');
        $q->where('g.id = ?', $this->gallery_media);
        $m = $q->fetchOne();
        $this->_set('Gallery', $m);
      }
      return $this->_get('Gallery');
    }
  }
  public function getType()
  {
    if ($this->photo_media instanceof majaxMediaPhoto || $this->photo_media > 0)
    {
      return 'Photo';
    }
    if ($this->video_media > 0)
    {
      return 'Video';
    }
    if ($this->audio_media > 0)
    {
      return 'Audio';
    }
    if ($this->gallery_media > 0)
    {
      return 'Gallery';
    }
  }
}
