<?php

/**
 * PluginmajaxMediaGalleryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmajaxMediaGalleryTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginmajaxMediaGalleryTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginmajaxMediaGallery');
  }
}