<?php

/**
 * PluginmajaxMediaGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmajaxMediaGallery extends BasemajaxMediaGallery
{
  public function postSave($event)
  {
    if ($this->MediaRegistryEntry == null)
    {
      $mre = new majaxMediaRegistryEntry();
      $mre->gallery_media = $this->id;
      $this->MediaRegistryEntry = $mre;
      $this->save();
    }
  }
  public function setUp()
  {
    parent::setUp();
    if (sfConfig::get('app_majaxMedia_publishable', false))
    {
      $publishabletemplate0 = new PublishableTemplate();
      $this->actAs($publishabletemplate0);
    }
  }

  protected $contentChanged = false;
  public function setContent($content)
  {
    if ($this->content != $content)
    {
      $this->_set('content', $content);
      $this->_set('content_html', majaxMarkdown::transform($content));
      $this->contentChanged = true;
    }
  }
  public function setContentHtml($content_html, $override = false)
  {
    if (!$this->contentChanged || $override == true)
      $this->_set('content_html', $content_html);
  }
}
