<?php

/**
 * PluginmajaxMediaAudioTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmajaxMediaAudioTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginmajaxMediaAudioTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginmajaxMediaAudio');
  }
}