<?php

/**
 * PluginmajaxMediaRegistryEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmajaxMediaRegistryEntry extends BasemajaxMediaRegistryEntry
{
  public function assignDefaultValues($overwrite = false)
  {
    parent::assignDefaultValues($overwrite);
    $this->uuid = majaxMediaToolbox::uuid('mre:');
  }
  public function getObject($deep = false)
  {
    if ($this->photo_media > 0)
    {
      $q = Doctrine_Query::create()->from('majaxMediaPhoto m');
      if ($deep)
      {
        $q->leftJoin('m.CreatedBy cb')->leftJoin('m.LastUpdatedBy lub');
      }
      $q->where('m.id = ?', $this->photo_media);
      $m = $q->fetchOne();
      $this->Photo = $m;
      return $this->Photo;
    }
    if ($this->video_media > 0)
    {
      $q = Doctrine_Query::create()->from('majaxMediaVideo m');
      if ($deep)
      {
        $q->leftJoin('m.CreatedBy cb')->leftJoin('m.LastUpdatedBy lub');
      }
      $q->where('m.id = ?', $this->video_media);
      $m = $q->fetchOne();
      $this->Video = $m;
      return $this->Video;
    }
    if ($this->audio_media > 0)
    {
      $q = Doctrine_Query::create()->from('majaxMediaAudio m');
      if ($deep)
      {
        $q->leftJoin('m.CreatedBy cb')->leftJoin('m.LastUpdatedBy lub');
      }
      $q->where('m.id = ?', $this->audio_media);
      $m = $q->fetchOne();
      $this->Audio = $m;
      return $this->Audio;
    }
    if ($this->gallery_media > 0)
    {
      $q = Doctrine_Query::create()->from('majaxMediaGallery g');
      if ($deep)
      {
        $q->leftJoin('g.CreatedBy cb')->leftJoin('g.LastUpdatedBy lub');
      }
      $q->where('g.id = ?', $this->gallery_media);
      $m = $q->fetchOne();
      $this->Gallery = $m;
      return $this->Gallery;
    }
  }
  public function getType()
  {
    if ($this->photo_media instanceof majaxMediaPhoto || $this->photo_media > 0)
    {
      return 'Photo';
    }
    if ($this->video_media instanceof majaxMediaVideo || $this->video_media > 0)
    {
      return 'Video';
    }
    if ($this->audio_media instanceof majaxMediaAudio || $this->audio_media > 0)
    {
      return 'Audio';
    }
    if ($this->gallery_media instanceof majaxMediaGallery || $this->gallery_media > 0)
    {
      return 'Gallery';
    }
  }
}
