<?php

/**
 * PluginmajaxMediaGalleryItem
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmajaxMediaGalleryItem extends BasemajaxMediaGalleryItem
{
  public function setUp()
  {
    $this->addListener(new majaxMediaGalleryItemListener(array('name' => 'position')));
  }

  public function preDqlSelect($event)
  {
    $params = $event->getParams();
    $field = $params['alias'] . '.position';
    $q = $event->getQuery();
    $q->orderBy($field . ' ASC');
  }
}
