<?php

/**
 * PluginmajaxMediaGalleryItemTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmajaxMediaGalleryItemTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginmajaxMediaGalleryItemTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginmajaxMediaGalleryItem');
  }
}