generator:
  class: sfDoctrineGenerator
  param:
    model_class:           majaxMediaPhoto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          photo
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css: none

    config:
      actions: ~
      fields:
        publishable: { label: Approved?, help: Is this photo cleared for publishing? }
        publish_on: { help: When can we publish this photo? }
        publish_until: { help: "If we should make this photo unavailable, when?" }
        areas_list: { label: Publish To }
        content: { label: Caption }
      list:
        title: List Photos
        fields:
          is_published: { renderer: ['dcmsTemplateHelper', 'showBoolean'] }
        display: [=name, created_at, updated_at]
        sort: [updated_at, desc]
      filter:  ~
      form:    ~
      edit:
        title: Edit Photo
      new:
        title: Add Photo
